### ISSUE TITLE
Captain Selection

### ISSUE THREAD

**Issue by Snakeren** [WessTorn/HnsMatchSystem#1]
I could not make "captain selection" to work even with /captain command. Can you help me what to do?

**Comment by WessTorn** [comment]
Hey captain mod only works on the knife map _35hp_2_
The knife map can be changed in the file `HnsMatchSystem/scripting/include/hns-match/globals.inc` in line 9

**Comment by Magicher0ex** [comment]
I don't see where it saves the stats instead of survive time
After the round: run, dmg, stabs and etc. stats got lost.
So if we play 1 round with wintime 1 it's good (ahahaha)
I see you try to make return the stats to 0 every round, but it doesn't save stats anywhere.
