### ISSUE TITLE
Doesn't save the stats

### ISSUE THREAD

**Issue by Magicher0ex** [WessTorn/HnsMatchSystem#3]
I don't see where it saves the stats instead of survive time
After the round: run, dmg, stabs and etc. stats got lost.
So if we play 1 round with wintime 1 it's good (ahahaha)
I see you try to make return the stats to 0 every round, but it doesn't save stats anywhere.

**Comment by WessTorn** [comment]
Hey, I fixed survive time, all player statistics are updated at the end of the round and remain until the end of the game, at the end of the game a motd appears with the top players and statistics, then everything is reset.
I hope you understood me (google translate) :)

**Comment by Magicher0ex** [comment]
@WessTorn I tried some matches, but it's the same thing. At the end of the match. It only shows the last round's statistics but not the all time.

**Comment by Magicher0ex** [comment]
@WessTorn Restart Round Stats are good but at the end it gets only the last round of stats and those before are just lost (instead of survive time of course)

**Comment by WessTorn** [comment]
@Magicher0ex yes, I  get it, I'll fix it later

**Comment by WessTorn** [comment]
@Magicher0ex fixed, check

**Comment by WessTorn** [comment]
but no, there are problems with showingo.
I will try to fix it soon.

**Comment by Magicher0ex** [comment]
> but no, there are problems with showingo.
> I will try to fix it soon.

What's the problem?

**Comment by WessTorn** [comment]
@Magicher0ex last fix

**Comment by Magicher0ex** [comment]
Why it shows only 5 players?
