### ISSUE TITLE
Приветствую, не могу скомпилировать файл sma уходит в ошибку.

### ISSUE THREAD

**Issue by weekqzxc** [WessTorn/HnsMatchSystem#7]
Если есть такая возможность отправьте файл amxx буду очень благодарен, не силен в этом.

**Comment by WessTorn** [comment]
Какой компилятор вы использовали?
Какие ошибки у вас были при компилировании?

**Comment by weekqzxc** [comment]
amxx обычный компилятор, ошибки не показывал. не умею похоже делать это. искал полностью уже скомпилированый не нашел.

**Comment by WessTorn** [comment]
Вот статья о том как компилировать плагин https://dev-cs.ru/threads/246/
В папке где лежит компилятор (scripting) не забудьте загрузить инклуды (include) плагина и инклуды модулей
https://github.com/WessTorn/HnsMatchSystem/tree/main/scripting/include (Эту папку объеденить с папкой include в компиляторе)
https://dev-cs.ru/resources/73/updates (/addons/amxmodx/scripting/include/ объеденить обьеденить с папкой include в компиляторе)
Попробуйте скомпилировать с помощью compile.exe что-бы посмотреть что будет писать.
