### ISSUE TITLE
failed

### ISSUE THREAD

**Issue by Stylish3** [WessTorn/HnsMatchSystem#8]
addons\amxmodx\scripting\include\hns-match/utils.inc(129) : error 021: symbol already defined: "rg_remove_entity"
addons\amxmodx\scripting\include\hns-match/utils.inc(129) : error 001: expected token: "=", but found "["
amxmodx\scripting\include\hns-match/utils.inc(131) : error 010: invalid function or declaration
addons\amxmodx\scripting\include\hns-match/utils.inc(136) : error 021: symbol already defined: "set_member_game"
addons\amxmodx\scripting\HnsMatchSystem.sma(138) : error 035: argument type mismatch (argument 1)
addons\amxmodx\scripting\HnsMatchSystem.sma(130) : warning 203: symbol is never used: "iEntity"

help pls ult.inc failed

**Comment by WessTorn** [comment]
fixed, check
